

[functions.declaration]
declaration.marker = "@" #could also be something like "func " - if you want the word to come before the function a space is required
args.delimeters = ["(", ")"]
args.seperator = ","
body.delimeters = ["{", "}"]


[functions.calling]
args.delimeters = ["(", ")"]
args.seperator = ","
builltin.marker.enabled = true #if builtin marker is disabled compiler performance will degrade significantly
builtin.marker.value = "!"
builtin.marker.location = "end" #can also be set to beginning

[ifs]
if.declaration.delimeters = ["(", ")"] #can be set to a blank string to not use if declaration delims - degrades compiler performance
if.body.delimeters = ["{", "}"] #could also be ["then", "endif"]

[fors]
for.declaration.delimeters = ["(", ")"]
for.body.delimeters = ["{", "}"]
