
[function.declaration]
marker = "@" #could also be something like "func " - if you want the word to come before the function a space is required
args.delimeters = ["(", ")"]
args.seperator = ","
body.delimeters = ["{", "}"]


[function.calling]
args.delimeters = ["(", ")"]
args.seperator = ","
builtin.marker.enabled = true #if builtin marker is disabled compiler performance will degrade significantly
builtin.marker.value = "!"
builtin.marker.location = "end" #can also be set to beginning

[loop.for]
declaration.delimeters = ["(", ")"]
body.delimeters = ["{", "}"]

[if]
declaration.delimeters = ["(", ")"] #can be set to a blank string to not use if declaration delims - degrades compiler performance
body.delimeters = ["{", "}"] #could also be ["then", "endif"]


